export const Images = {
  loginBackground: require('./login-bg.png'),
  signupBackground: require('./signup-bg.png'),
  logo: require('./logo.png'),
  splash1: require('./splash-1.jpg'),
  splash2: require('./splash-2.jpg'),
  splash3: require('./splash-3.jpg'),
  splash4: require('./splash-4.jpg'),
  banner1: require('./banner-1.jpg'),
  banner2: require('./banner-2.jpg'),
  banner3: require('./banner-3.jpg'),
  banner4: require('./banner-4.jpg'),
  vegetable: require('./vegetable.png'),
  fruits: require('./fruits.png'),
  beverages: require('./beverages.png'),
  grocery: require('./grocery.png'),
  edibleOil: require('./edible-oil.png'),
  household: require('./household.png'),
  firstTimeLogin: require('./first-login-bg.png'),
};
