export const QUERY_KEY = {
  PRODUCTS: 'PRODUCTS',
  PRODUCT_SEARCH: 'PRODUCT_SEARCH',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  CATEGORIES: 'CATEGORIES',
  CART: 'CART',
  PRODUCT_UNITS: 'PRODUCT_UNITS',
};

export const SECURE_STORE = {
  AUTH_TOKEN: 'AUTH_TOKEN',
  OTP_TOKEN: 'OTP_TOKEN',
};
