name: C-Store APP CI

on:
  pull_request:
    branches: [main, preview, dev]
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4 # clones repo into the GitHub Actions runner
        with:
          fetch-depth: 2 # fetch only the last 2 commits

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo # This specific what to cache
          key: ${{ runner.os }}-turbo-${{ github.sha }} # Create a unique key
          restore-keys: | # Restore the cache if key is not found
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v3 # installs the pnpm packages manager in the runner environment
        with:
          version: 8 # pnpm version

      - name: Setup Node.js environment
        uses: actions/setup-node@v4 # setup Node.js environment
        with:
          node-version: 20 # node version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
